-- 01
use PEDIDOS

/* 02 Liste os campos NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL de PEDIDOS, seguidos de
NOME do vendedor; */
SELECT
	NUM_PEDIDO, DATA_EMISSAO, VLR_TOTAL, TB_VENDEDOR.NOME
FROM TB_PEDIDO
	INNER JOIN TB_VENDEDOR
ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN


/* 03 */
SELECT
	NUM_PEDIDO, DATA_EMISSAO, VLR_TOTAL, TB_CLIENTE.NOME
FROM TB_PEDIDO
	INNER JOIN TB_CLIENTE
ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI

/* 04 */
SELECT  
	NUM_PEDIDO, V.NOME NOME_VENDEDOR, C.NOME NOME_CLIENTE
FROM TB_PEDIDO P
  JOIN TB_VENDEDOR V ON P.CODVEN = V.CODVEN
  JOIN TB_CLIENTE C ON P.CODCLI = C.CODCLI

/* 05 Liste os itens de pedido (ITENSPEDIDO) com o nome do produto */
SELECT 
  DESCRICAO
FROM TB_ITENSPEDIDO
 INNER JOIN TB_PRODUTO
ON TB_ITENSPEDIDO.COD_PRODUTO = TB_PRODUTO.COD_PRODUTO



/* 06 Liste os campos COD_PRODUTO e DESCRICAO da tabela PRODUTOS, seguidos da
descrição do tipo de produto;  ph*/
SELECT COD_PRODUTO, DESCRICAO,TB_TIPOPRODUTO.TIPO DESCRICAO_TIPO

FROM TB_PRODUTO 
INNER JOIN TB_TIPOPRODUTO
ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO

/* 07 */

SELECT COD_PRODUTO, 
	DESCRICAO,
	TB_TIPOPRODUTO.TIPO DESCRICAO_TIPO ,
	TB_PRODUTO.COD_UNIDADE, 
	TB_UNIDADE.UNIDADE 

FROM TB_PRODUTO 
INNER JOIN TB_TIPOPRODUTO ON TB_PRODUTO.COD_TIPO = TB_TIPOPRODUTO.COD_TIPO
INNER JOIN TB_UNIDADE ON TB_PRODUTO.COD_UNIDADE = TB_UNIDADE.COD_UNIDADE

	
/* 10 Liste todos os pedidos (PEDIDOS) do vendedor MARCELO em Jan/2017; */
SELECT
   TB_PEDIDO.NUM_PEDIDO, TB_VENDEDOR.NOME, TB_PEDIDO.DATA_EMISSAO
FROM TB_PEDIDO
   JOIN TB_VENDEDOR ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN
WHERE TB_VENDEDOR.NOME = 'MARCELO' AND TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31'

/* 11. Liste os nomes dos clientes que efetuaram compras em janeiro de 2017; */
SELECT
   TB_CLIENTE.NOME NOME_CLIENTE, TB_PEDIDO.DATA_EMISSAO COMPRA_EM_JANEIRO
FROM TB_PEDIDO
   JOIN TB_CLIENTE ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI
WHERE TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31'

/* 12. Liste os nomes de produtos que foram vendidos em janeiro de 2017; */
SELECT
   TB_PRODUTO.DESCRICAO, TB_PEDIDO.DATA_EMISSAO VENDAS_EM_JANEIRO
FROM TB_PRODUTO
   JOIN TB_PEDIDO ON TB_PEDIDO.CODCLI = TB_PRODUTO.ID_PRODUTO
WHERE TB_PEDIDO.DATA_EMISSAO BETWEEN '2017.1.1' AND '2017.1.31'
